import { Client, MeasurementSnapshot, Order, HotspotDefinition, GarmentTemplate, AppSettings } from '@/types';

export const DEFAULT_HOTSPOTS: HotspotDefinition[] = [
  {
    key: 'neck',
    label: 'Neck Circumference',
    view: 'front',
    category: 'head_neck',
    frontX: 150,
    frontY: 82,
    hint: 'Measure around the base of the neck where the collar rests, inserting one finger for ease.',
  },
  {
    key: 'shoulder_width',
    label: 'Shoulder Width',
    view: 'both',
    category: 'upper_body',
    frontX: 150,
    frontY: 104,
    backX: 150,
    backY: 104,
    hint: 'Measure across the back from shoulder bone tip to shoulder bone tip.',
  },
  {
    key: 'bust_chest',
    label: 'Bust / Chest',
    view: 'front',
    category: 'upper_body',
    frontX: 150,
    frontY: 142,
    hint: 'Measure around the fullest part of the chest/bust, keeping the tape level across the back.',
  },
  {
    key: 'waist',
    label: 'Waist Circumference',
    view: 'both',
    category: 'upper_body',
    frontX: 150,
    frontY: 198,
    backX: 150,
    backY: 198,
    hint: 'Measure around the natural narrowest waistline, just above the belly button.',
  },
  {
    key: 'hip',
    label: 'Hip Circumference',
    view: 'both',
    category: 'lower_body',
    frontX: 150,
    frontY: 248,
    backX: 150,
    backY: 248,
    hint: 'Measure around the widest point of the hips and buttocks.',
  },
  {
    key: 'torso_length',
    label: 'Front Torso Length',
    view: 'front',
    category: 'upper_body',
    frontX: 150,
    frontY: 172,
    hint: 'Measure from the hollow of the neck / collarbone down to the natural waistline.',
  },
  {
    key: 'sleeve_length',
    label: 'Sleeve Length',
    view: 'front',
    category: 'arms',
    frontX: 88,
    frontY: 200,
    hint: 'Measure from the shoulder point along the bent arm down to the wrist bone.',
  },
  {
    key: 'arm_length',
    label: 'Full Arm Length',
    view: 'front',
    category: 'arms',
    frontX: 84,
    frontY: 245,
    hint: 'Measure from the shoulder tip straight down to just past the wrist bone.',
  },
  {
    key: 'wrist',
    label: 'Wrist Circumference',
    view: 'front',
    category: 'arms',
    frontX: 74,
    frontY: 292,
    hint: 'Measure snugly around the wrist bone, adding ease as preferred.',
  },
  {
    key: 'thigh',
    label: 'Thigh Circumference',
    view: 'front',
    category: 'lower_body',
    frontX: 126,
    frontY: 308,
    hint: 'Measure around the fullest part of the upper thigh, just below the crotch.',
  },
  {
    key: 'inseam',
    label: 'Inseam Length',
    view: 'front',
    category: 'lower_body',
    frontX: 142,
    frontY: 410,
    hint: 'Measure from the lowest point of the crotch down the inner leg to the shoe top.',
  },
  {
    key: 'ankle',
    label: 'Ankle Circumference',
    view: 'front',
    category: 'lower_body',
    frontX: 122,
    frontY: 530,
    hint: 'Measure around the ankle bone or desired trouser cuff opening.',
  },
  {
    key: 'back_width',
    label: 'Back Width',
    view: 'back',
    category: 'upper_body',
    backX: 150,
    backY: 146,
    hint: 'Measure horizontally across the shoulder blades between armscye seams.',
  },
  {
    key: 'nape_to_waist',
    label: 'Nape to Waist',
    view: 'back',
    category: 'upper_body',
    backX: 150,
    backY: 178,
    hint: 'Measure vertically from prominent neck bone (C7) straight down to the natural waist.',
  },
];

export const DEFAULT_TEMPLATES: GarmentTemplate[] = [
  {
    id: 'bespoke_african_gown',
    name: 'Bespoke African Gown',
    fieldKeys: ['neck', 'shoulder_width', 'bust_chest', 'waist', 'hip', 'sleeve_length', 'arm_length', 'thigh', 'inseam'],
    description: 'Bespoke traditional African couture gown, bridal styles, corset-backed silhouettes, and embellished trains.',
  },
  {
    id: 'suit',
    name: 'Full 2-Piece Suit',
    fieldKeys: [
      'neck',
      'shoulder_width',
      'bust_chest',
      'waist',
      'hip',
      'sleeve_length',
      'arm_length',
      'wrist',
      'back_width',
      'nape_to_waist',
      'thigh',
      'inseam',
      'ankle',
    ],
    description: 'Full bespoke tailoring coverage for two-piece jacket and trouser ensembles.',
  },
  {
    id: 'agbada',
    name: 'Traditional Agbada / Kaftan',
    fieldKeys: ['neck', 'shoulder_width', 'bust_chest', 'arm_length', 'torso_length', 'inseam'],
    description: 'Flowing grand boubou, agbada outer robe, and matching tailored kaftan tunic & trousers.',
  },
  {
    id: 'gown',
    name: 'Gown / Dress',
    fieldKeys: ['bust_chest', 'waist', 'hip', 'shoulder_width', 'torso_length', 'nape_to_waist', 'inseam'],
    description: 'Evening wear, gala dresses, bridal silhouettes, and structured corsetry.',
  },
  {
    id: 'trousers',
    name: 'Trousers / Slacks',
    fieldKeys: ['waist', 'hip', 'thigh', 'inseam', 'ankle'],
    description: 'Fittings for tailored dress pants, pleated trousers, and custom chinos.',
  },
  {
    id: 'shirt',
    name: 'Shirt / Blouse',
    fieldKeys: ['neck', 'shoulder_width', 'bust_chest', 'waist', 'sleeve_length', 'wrist', 'torso_length'],
    description: 'Essential measurements for bespoke dress shirts, casual button-downs, and tailored blouses.',
  },
  {
    id: 'all',
    name: 'All Available Points',
    fieldKeys: DEFAULT_HOTSPOTS.map((h) => h.key),
    description: 'Complete anatomical capture covering all upper and lower body measurement points.',
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  defaultUnit: 'cm',
  currency: '₦',
  customFields: [
    {
      key: 'bicep',
      label: 'Bicep Circumference',
      view: 'front',
      category: 'arms',
      frontX: 98,
      frontY: 158,
      hint: 'Measure around the fullest part of the flexed or relaxed upper arm.',
      isCustom: true,
    },
    {
      key: 'calf',
      label: 'Calf Circumference',
      view: 'both',
      category: 'lower_body',
      frontX: 120,
      frontY: 450,
      backX: 120,
      backY: 450,
      hint: 'Measure around the fullest part of the calf muscle.',
      isCustom: true,
    },
  ],
  templates: DEFAULT_TEMPLATES,
};

export const SAMPLE_CLIENTS: Client[] = [
  {
    id: 'c-1',
    name: 'Chloe Dallas',
    phone: '+234 803 456 7890',
    email: 'chloe.dallas@couture-lagos.com',
    notes: 'Bespoke African Gown commission with hand-stitched beaded embroidery and train.',
    createdAt: '2026-06-12T10:00:00.000Z',
  },
  {
    id: 'c-2',
    name: 'Taylor Razaq',
    phone: '+234 812 345 6789',
    email: 'taylor.razaq@atelier.ng',
    notes: 'Double-breasted jacket and tailored trousers in Italian wool.',
    createdAt: '2026-07-04T14:30:00.000Z',
  },
  {
    id: 'c-3',
    name: 'Bryan Muhammed',
    phone: '+234 905 123 4567',
    email: 'b.muhammed@heritage.ng',
    notes: 'Bespoke African Gown and gold-threaded Agbada with monogram cuff.',
    createdAt: '2026-08-15T09:15:00.000Z',
  },
  {
    id: 'c-4',
    name: 'Adriana Kunle',
    phone: '+234 802 987 6543',
    email: 'adriana.kunle@vogue.ng',
    notes: 'Prefers silk faille drape with architectural back pleats.',
    createdAt: '2026-08-28T16:00:00.000Z',
  },
  {
    id: 'c-5',
    name: 'Marcus Vance',
    phone: '+234 809 876 5432',
    email: 'm.vance@architectural.net',
    notes: 'Bespoke structured senator ensemble with high collar.',
    createdAt: '2026-09-02T11:45:00.000Z',
  },
];

export const SAMPLE_SNAPSHOTS: MeasurementSnapshot[] = [
  {
    id: 'ms-1',
    clientId: 'c-1',
    date: '2026-08-20',
    unit: 'cm',
    garmentType: 'Gown / Dress',
    notes: 'Summer couture fitting for Autumn Gala. High heel allowance: 8.5cm.',
    measurements: {
      neck: 34,
      shoulder_width: 39,
      bust_chest: 88,
      waist: 68,
      hip: 94,
      torso_length: 37,
      nape_to_waist: 39,
      inseam: 82,
      sleeve_length: 58,
      arm_length: 56,
      wrist: 15,
      ankle: 22,
    },
  },
  {
    id: 'ms-2',
    clientId: 'c-2',
    date: '2026-08-25',
    unit: 'cm',
    garmentType: 'Full 2-Piece Suit',
    notes: 'Savile Row cut fitting. Left shoulder slightly lower by 0.7cm.',
    measurements: {
      neck: 41,
      shoulder_width: 47,
      bust_chest: 104,
      waist: 86,
      hip: 102,
      torso_length: 44,
      back_width: 43,
      nape_to_waist: 45,
      sleeve_length: 64,
      arm_length: 62,
      wrist: 18,
      thigh: 58,
      inseam: 83,
      ankle: 23,
      bicep: 34,
    },
  },
  {
    id: 'ms-3',
    clientId: 'c-3',
    date: '2026-09-01',
    unit: 'in',
    garmentType: 'Gown / Dress',
    notes: 'Silk crepe bias fitting. Low back dip requested.',
    measurements: {
      bust_chest: 34,
      waist: 26.5,
      hip: 37,
      shoulder_width: 15.5,
      torso_length: 14.5,
      nape_to_waist: 15,
      inseam: 32,
    },
  },
  {
    id: 'ms-4',
    clientId: 'c-5',
    date: '2026-09-03',
    unit: 'cm',
    garmentType: 'Shirt / Blouse',
    notes: 'Performance concert shirts. Extra pleated back ease.',
    measurements: {
      neck: 39.5,
      shoulder_width: 45,
      bust_chest: 98,
      waist: 82,
      sleeve_length: 65,
      wrist: 17.5,
      torso_length: 42,
    },
  },
];

export const SAMPLE_ORDERS: Order[] = [
  {
    id: 'ord-101',
    clientId: 'c-1',
    garmentType: 'Bespoke African Gown',
    measurementSnapshotId: 'ms-1',
    referenceImages: [
      {
        id: 'img-1',
        url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=600&q=80',
        title: 'Couture Silhouette Sketch',
        note: 'Silk faille drape with architectural back pleats.',
      },
      {
        id: 'img-2',
        url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80',
        title: 'Fabric Swatch',
        note: 'Ivory duchess satin with champagne undertones.',
      },
    ],
    price: 185000,
    notes: 'Hand-stitched, monogram design on wrist and gold buttons.',
    status: 'Pending',
    pickupDateTime: '2026-09-23T16:00:00.000Z',
    createdAt: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'ord-102',
    clientId: 'c-2',
    garmentType: 'Bespoke African Gown',
    measurementSnapshotId: 'ms-2',
    referenceImages: [
      {
        id: 'img-3',
        url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80',
        title: 'Lapel Reference',
        note: 'Peak lapels, 9.5cm width with hand-sewn Milanese buttonhole.',
      },
      {
        id: 'img-4',
        url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
        title: 'Fabric Swatch',
        note: 'Dark charcoal herringbone, Holland & Sherry Super 130s.',
      },
    ],
    price: 240000,
    notes: 'Final fitting approved, gold thread embroidery complete.',
    status: 'Completed',
    pickupDateTime: '2026-09-17T14:00:00.000Z',
    createdAt: '2026-08-26T11:30:00.000Z',
  },
  {
    id: 'ord-103',
    clientId: 'c-3',
    garmentType: 'Bespoke African Gown',
    measurementSnapshotId: 'ms-3',
    referenceImages: [
      {
        id: 'img-5',
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
        title: 'Inspiration Lookbook',
        note: 'Minimalist column cut with soft cowl neckline.',
      },
    ],
    price: 120000,
    notes: 'Fabric shipment delayed from artisan weaver.',
    status: 'Paused',
    pickupDateTime: '2026-09-07T18:00:00.000Z',
    createdAt: '2026-09-01T15:00:00.000Z',
  },
  {
    id: 'ord-104',
    clientId: 'c-5',
    garmentType: 'Shirt / Blouse',
    measurementSnapshotId: 'ms-4',
    referenceImages: [
      {
        id: 'img-6',
        url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=600&q=80',
        title: 'Collar Style',
        note: 'Cutaway collar with mother-of-pearl buttons.',
      },
    ],
    price: 480,
    notes: 'Set of two bespoke tuxedo shirts with Marcella bib front.',
    status: 'Ready',
    pickupDateTime: '2026-09-13T11:00:00.000Z', // Due THIS WEEK!
    createdAt: '2026-09-03T12:00:00.000Z',
  },
  {
    id: 'ord-105',
    clientId: 'c-4',
    garmentType: 'Gown / Dress',
    referenceImages: [
      {
        id: 'img-7',
        url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=600&q=80',
        title: 'Embroidery Swatch',
        note: 'Gold thread geometric borders on emerald silk velvet.',
      },
    ],
    price: 3100,
    notes: 'Hand embroidery underway at partner atelier. Estimated completion mid-September.',
    status: 'In Progress',
    pickupDateTime: '2026-09-18T15:30:00.000Z', // Next week
    createdAt: '2026-08-30T10:00:00.000Z',
  },
  {
    id: 'ord-106',
    clientId: 'c-2',
    garmentType: 'Trousers / Slacks',
    referenceImages: [],
    price: 520,
    notes: 'Classic British high-waisted trousers with side adjusters. Successfully collected.',
    status: 'Picked Up',
    pickupDateTime: '2026-08-15T16:00:00.000Z',
    createdAt: '2026-07-28T09:00:00.000Z',
  },
];

export const PRESET_IMAGE_SWATCHES = [
  {
    title: 'Super 130s Navy Wool',
    url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80',
    note: 'Dark navy twill, lightweight 260g four-season wool.',
  },
  {
    title: 'Duchess Satin Ivory',
    url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80',
    note: 'Lustrous heavyweight silk satin for structured eveningwear.',
  },
  {
    title: 'Charcoal Herringbone',
    url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
    note: 'Traditional British woolen spun weave for autumn coats.',
  },
  {
    title: 'Emerald Silk Velvet',
    url: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=600&q=80',
    note: 'Rich pile drape with deep luster for formal gowns.',
  },
  {
    title: 'Atelier Tailoring Sketch',
    url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=600&q=80',
    note: 'Pencil design sketch showing silhouette balance & proportion.',
  },
];
